include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: false
    strict-inference: false
    strict-raw-types: false

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    avoid_print: true
    require_trailing_commas: false
