"""
نقطة دخول HuggingFace Space لِخادم quran-muaalem.
HuggingFace Space entry point for the quran-muaalem server.

HuggingFace يتوقّع app.py يخدم على المنفذ 7860. هذا الملف يُشغّل engine
(النموذج) في عملية خلفية ثم app على المنفذ 7860.

HuggingFace expects app.py to serve on port 7860. This script launches the
engine (model) in a background process, then the app on port 7860.

ملاحظة: HuggingFace CPU basic = 16GB RAM. النموذج 2.4GB + torch + المعالجة قد
يحتاج ذاكرة أكبر. إن فشل التحميل، جرّب الترقية لِـ "CPU upgraded" أو GPU.
"""

import os
import signal
import subprocess
import sys
import time

# HuggingFace يضبط ACCELERATOR=zero افتراضياً، لكن quran-muaalem يقبل
# cpu/cuda/mps فقط. أجبرها على cpu قبل قراءة أي إعدادات.
os.environ["ACCELERATOR"] = "cpu"
os.environ["DTYPE"] = "float16"

PORT = 7860  # المنفذ الذي يتوقّعه HuggingFace.


def _install_mcp_guard():
    """اكتب sitecustomize.py لِحظر fastmcp/mcp في كل عملية Python فرعية.

    Write sitecustomize.py to block fastmcp/mcp in every child Python process.

    litserve 0.2.17 يفحص fastmcp لِتحديد توفّر MCP. إن وُجدت، يستورد MCPServer
    من mcp.server.lowlevel، لكنّ mcp على HuggingFace بإصدار غير متوافق فينهار
    بِـ NameError. Python تُحمّل sitecustomize.py تلقائياً عند بدء كل عملية،
    فالـ patch يُطبَّق على engine و app معاً.

    litserve 0.2.17 checks fastmcp for MCP availability. If present, it imports
    MCPServer from mcp.server.lowlevel, but mcp on HuggingFace is an incompatible
    version, crashing with NameError. Python auto-loads sitecustomize.py at every
    process start, so the patch applies to both engine and app.
    """
    import site

    code = (
        "# Auto-generated by app.py — litserve MCP bug workaround.\n"
        "try:\n"
        "    import importlib.util as _u, sys as _s\n"
        "    _spec = _u.find_spec('litserve.utils')\n"
        "    if _spec is not None:\n"
        "        _mod = _u.module_from_spec(_spec)\n"
        "        _spec.loader.exec_module(_mod)\n"
        "        _orig = _mod.is_package_installed\n"
        "        _mod.is_package_installed = (\n"
        "            lambda n, *a, **k: False if n in ('fastmcp', 'mcp')\n"
        "            else _orig(n, *a, **k))\n"
        "        _s.modules['litserve.utils'] = _mod\n"
        "except Exception:\n"
        "    pass\n"
    )
    # اكتب في كل مجلدات site-packages لضمان التحميل.
    for sp_dir in site.getsitepackages() + [site.getusersitepackages()]:
        try:
            with open(os.path.join(sp_dir, "sitecustomize.py"), "w") as f:
                f.write(code)
            print(f"  wrote sitecustomize → {sp_dir}", flush=True)
        except Exception:
            pass


def main():
    print("===== Application Startup =====", flush=True)
    print(f"ACCELERATOR={os.environ.get('ACCELERATOR')}", flush=True)
    print(f"DTYPE={os.environ.get('DTYPE')}", flush=True)

    # 1) احذف fastmcp + mcp، واكتب sitecustomize لِحظرها في العمليات الفرعية.
    print("=== Installing MCP guard ===", flush=True)
    try:
        subprocess.run(
            [sys.executable, "-m", "pip", "uninstall", "-y",
             "fastmcp", "mcp"],
            capture_output=True, timeout=120,
        )
    except Exception:
        pass
    _install_mcp_guard()
    print("✅ MCP guard installed (litserve bug workaround)", flush=True)

    # 2) شغّل engine على منفذ داخلي 8000.
    print("=== Starting engine on port 8000 ===", flush=True)
    env = os.environ.copy()
    env["PORT"] = "8000"
    env["ACCELERATOR"] = "cpu"
    env["DTYPE"] = "float16"
    engine_proc = subprocess.Popen(
        [sys.executable, "-u", "-m", "quran_muaalem.engine.main"],
        env=env,
        stdout=sys.stdout,
        stderr=sys.stderr,
    )

    # 3) انتظر حتى يصبح engine جاهزاً (حتى 5 دقائق لِتحميل النموذج 2.4GB).
    import urllib.request

    print("=== Waiting for engine model to load (up to 5 min)... ===",
          flush=True)
    engine_ready = False
    for i in range(60):  # 60 × 5s = 5 min
        time.sleep(5)
        try:
            urllib.request.urlopen("http://127.0.0.1:8000/health", timeout=3)
            print(f"✅ Engine ready after {(i+1)*5}s", flush=True)
            engine_ready = True
            break
        except Exception:
            if engine_proc.poll() is not None:
                print(f"❌ Engine process died (exit code "
                      f"{engine_proc.returncode})!", flush=True)
                sys.exit(1)
            print(f"    loading model... ({(i+1)*5}s)", flush=True)

    if not engine_ready:
        print("❌ Engine failed to start within 5 minutes", flush=True)
        engine_proc.terminate()
        sys.exit(1)

    # 4) شغّل app على المنفذ 7860.
    print(f"=== Starting app on port {PORT} ===", flush=True)
    app_env = os.environ.copy()
    app_env["PORT"] = str(PORT)
    app_env["HOST"] = "0.0.0.0"
    app_env["ACCELERATOR"] = "cpu"
    app_env["ENGINE_URL"] = "http://127.0.0.1:8000/predict"

    app_proc = subprocess.Popen(
        [sys.executable, "-u", "-m", "quran_muaalem.app.main"],
        env=app_env,
        stdout=sys.stdout,
        stderr=sys.stderr,
    )

    # 5) أبقِ السكربت حيّاً.
    def shutdown(_signum, _frame):
        engine_proc.terminate()
        app_proc.terminate()
        sys.exit(0)

    signal.signal(signal.SIGTERM, shutdown)
    signal.signal(signal.SIGINT, shutdown)

    app_proc.wait()


if __name__ == "__main__":
    main()
